function lme_save(sheetName, lmeTbls, varargin)
% LME_SAVE Exports pre-formatted LME analysis results to an Excel spreadsheet.
%
%   LME_SAVE(SHEETNAME, LMETBLS) 
%   takes an array of structured tables (generated by lme_mdl2tbls) and 
%   saves them into a single, well-organized worksheet named SHEETNAME.
%
%   Optional Parameters:
%       pathName - Directory path (default: 'D:\OneDrive - Tel-Aviv University\PhD\Slutsky\Manuscripts\MCU\Results')
%       xlsName  - Excel file name (default: 'mcu_suppTbl.xlsx')
%       verbose  - Print progress (default: true)

%% ========================================================================
%  ARGUMENTS
%  ========================================================================

p = inputParser;
addRequired(p, 'sheetName', @(x) ischar(x) || isstring(x));
addRequired(p, 'lmeTbls', @isstruct);

% Default path and name as requested
defaultPath = 'D:\OneDrive - Tel-Aviv University\PhD\Slutsky\Manuscripts\MCU\Results';
defaultXls = 'mcu_suppTbl.xlsx';

addParameter(p, 'pathName', defaultPath, @(x) ischar(x) || isstring(x));
addParameter(p, 'xlsName', defaultXls, @(x) ischar(x) || isstring(x));
addParameter(p, 'verbose', true, @islogical);

parse(p, sheetName, lmeTbls, varargin{:});

sheetName = char(p.Results.sheetName);
pathName  = char(p.Results.pathName);
xlsName   = char(p.Results.xlsName);
verbose   = p.Results.verbose;

if isempty(pathName), pathName = pwd; end
if ~endsWith(xlsName, '.xlsx', 'IgnoreCase', true)
    xlsName = [char(xlsName), '.xlsx'];
end

% Construct full file path
fullXlsPath = fullfile(pathName, xlsName);

if verbose
    fprintf('[LME_SAVE] Exporting results to %s (Sheet: %s)...\n', fullXlsPath, sheetName);
end

% Ensure directory exists
if ~isfolder(pathName)
    mkdir(pathName);
end

%% ========================================================================
%  PREPARE SPREADSHEET CONTENT
%  ========================================================================

exportData = {};

for iTbl = 1:length(lmeTbls)
    tblStruct = lmeTbls(iTbl);
    tbl = tblStruct.Table;
    
    if isempty(tbl) || height(tbl) == 0
        continue;
    end
    
    % Add Title
    exportData{end+1} = {tblStruct.Title};
    
    % Add Headers
    exportData{end+1} = tbl.Properties.VariableNames;
    
    % Add Data
    tblCell = table2cell(tbl);
    
    % Convert datasets, arrays, or strings for cleaner writing
    for r = 1:size(tblCell, 1)
        for c = 1:size(tblCell, 2)
            val = tblCell{r,c};
            if isnumeric(val) && (length(val) > 1)
                tblCell{r,c} = char(join(string(val), ', ')); % cleaner array representation
            elseif isnumeric(val) && isnan(val)
                tblCell{r,c} = '';
            elseif islogical(val)
                if val, tblCell{r,c} = 'true'; else, tblCell{r,c} = 'false'; end
            elseif isstring(val) && ismissing(val)
                tblCell{r,c} = '';
            elseif iscategorical(val)
                tblCell{r,c} = char(val);
            elseif iscell(val) && numel(val) == 1
                tblCell{r,c} = val{1};
            end
        end
    end
    
    % Append into exportData
    for r = 1:size(tblCell, 1)
        exportData{end+1} = tblCell(r, :);
    end
    exportData{end+1} = {''}; % Empty row separator
end

%% ========================================================================
%  APPEND LOGIC FOR EXISTING SHEETS
%  ========================================================================

existingData = {};
if isfile(fullXlsPath)
    try
        % Safely get sheet names 
        sheets = sheetnames(fullXlsPath);
        if ismember(string(sheetName), sheets)
            % Read existing sheet
            existingData = readcell(fullXlsPath, 'Sheet', sheetName, 'DateType', 'text');
            
            % Sanitize existingData to replace 'missing' with empty strings
            % (prevents writecell from writing #N/A errors)
            if ~isempty(existingData)
                for r = 1:size(existingData, 1)
                    for c = 1:size(existingData, 2)
                        if ismissing(existingData{r,c})
                            existingData{r,c} = '';
                        end
                    end
                end
            end
        end
    catch
        % File might be locked or unreadable
    end
end

%% ========================================================================
%  WRITE TO EXCEL
%  ========================================================================

% Create a uniform rectangular cell array for the newly generated data
if isempty(exportData)
    if verbose; fprintf('[LME_SAVE] No data to export.\n'); end
    return;
end

maxCols = max(cellfun(@length, exportData));
numRows = length(exportData);

newDataBlock = cell(numRows, maxCols);
newDataBlock(:) = {''};

for iRow = 1:numRows
    rowLen = length(exportData{iRow});
    if rowLen > 0
        newDataBlock(iRow, 1:rowLen) = exportData{iRow};
    end
end

% Combine existing and new data if extending
if ~isempty(existingData)
    % Add a 2-row gap
    gapCols = max(size(existingData, 2), size(newDataBlock, 2));
    gapBlock = cell(2, gapCols);
    gapBlock(:) = {''};
    
    % Align columns of existing data
    if size(existingData, 2) < gapCols
        existingData{1, gapCols} = ''; 
    end
    
    % Align columns of new data
    if size(newDataBlock, 2) < gapCols
        newDataBlock{1, gapCols} = ''; 
    end
    
    finalBuffer = [existingData; gapBlock; newDataBlock];
else
    finalBuffer = newDataBlock;
end

% Write via writecell
writecell(finalBuffer, fullXlsPath, 'Sheet', sheetName);

if verbose
    fprintf('[LME_SAVE] Successfully saved Excel file to Sheet: %s\n', sheetName);
end

end % EOF